spring:
  application:
    name: faunora
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/faunora}
    username: ${SPRING_DATASOURCE_USERNAME:faunora}
    password: ${SPRING_DATASOURCE_PASSWORD:faunora}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  mail:
    host: smtp.gmail.com
    port: 587
    username: faunorasystem@gmail.com
    password: faunora123
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


api:
  services:
    time:
      duration: 30
    morning:
      start:
        time: 8
      ending:
        time: 12
    afternoon:
      start:
        time: 14
      ending:
        time: 18
  security:
    token:
      secret: lupita-gatinha-linda